### ISSUE TITLE
cpod crashes every time a make a search 

### ISSUE THREAD

**Issue by Lvaskz** [snapcrafters/cumulonimbus#2]
cpod crashes every time a make a search 
}ubuntu 18.04
64 bit 
gnome 3.28.1

**Comment by carlos-tovar** [comment]
Same, ubuntu 18.04, 64 bit, gnome 3.28.2

The issue is gone on cpod 1.17.0, but I had to launch Cpod by running  /snap/cumulonimbus/58/opt/CPod/cpod   directly as I was getting a file not found error

"/snap/cumulonimbus/58/bin/desktop-launch: line 544: /snap/cumulonimbus/58/opt/CPod/cumulonimbus: No such file or directory"

**Comment by YamiYukiSenpai** [comment]
I'm attaching [the output](https://github.com/snapcrafters/cumulonimbus/files/3140233/cumulonimbus_error.txt) after running `$ snap run cumulonimbus`.  Hope it helps.

**Comment by wenderRondonia** [comment]
the [repository](https://github.com/z-------------/CPod) from zack guard with the new version is already fixed, install from there

**Comment by YamiYukiSenpai** [comment]
Nope.  The Edge channel is already on 1.27.1.  It hasn't been updated since then.

**Comment by RickAndTired** [comment]
Stable and Edge both crash when clicking on Search or when Tabbing to the Search bar.
The Appimage works fine.

[cpod-stable.txt](https://github.com/snapcrafters/cumulonimbus/files/3612378/cpod-stable.txt)
[cpod-edge.txt](https://github.com/snapcrafters/cumulonimbus/files/3612379/cpod-edge.txt)

**Comment by merlijn-sebrechts** [comment]
This is fixed in the latest version in edge and will soon be published to stable. Thanks for reporting this!
